language: ruby
sudo: required
services: docker
cache: bundler
script:
- ./.build.sh
after_success:
- ./.publish.sh
dd:
- openssl aes-256-cbc -K $encrypted_8219e3a8c0b5_key -iv $encrypted_8219e3a8c0b5_iv
  -in config.json.enc -out ~\/.docker/config.json -d
